### ISSUE TITLE
Change the social card

### ISSUE THREAD

**Issue by pBouillon** [pBouillon/ngx-flagr#32]
## Issue Summary

The social card for the documentation project is still the one provided by default by docusaurus

When sharing a link, it should showcase a different image with `ngx-flagr`'s icon instead

## Category

```text
- [ ] Bug report
- [ ] Regression
- [ ] Feature suggestion
- [x] Documentation issue
- [ ] Other
```

## Expected Behavior

When sharing a link, it should showcase a different image with `ngx-flagr`'s icon instead, using the colors of the docusaurus palette (the light one)

Something following this layout (same as the default one):

![suggestion layout](https://github.com/pBouillon/ngx-flagr/assets/22640284/1b10c109-28fe-48cf-be97-1711e1c94d72)

## Actual Behavior

The image that is used for the preview is the following (`apps\docs-app\static\img\docusaurus-social-card.jpg`):

![docusaurus default](https://github.com/pBouillon/ngx-flagr/assets/22640284/e4561fcd-c8de-4dfb-940d-8b2ef259ea8e)

## Steps to Reproduce

- Go to [the documentation website](https://pbouillon.github.io/ngx-flagr/)
- Copy the link
- Share it on LinkedIn / Discord / Telegram / Twitter / etc.
- Observe the preview

## Environment

- Browser/Device: N/A
- Node version: N/A
- Version: N/A

**Comment by mintbomb27** [comment]
Hey! Can I work on this?

**Comment by pBouillon** [comment]
Hey, sure, thanks for your help

It could be better to keep the colors consistent but I fear this will look "errory" having red everywhere, we can still give it a try!

**Comment by mintbomb27** [comment]
Okay, Please take a look at https://www.figma.com/file/AAQ58ZY7lrijaGHYWeTdlY/Untitled?type=design&node-id=0%3A1&mode=design&t=GCrBvjLXep2oYPMe-1

**Comment by pBouillon** [comment]
The last one is looking good!
Could we keep the white background instead of a dark one (while still having the red gradient)?

Also, it might be out of scope but the "F" in the shield seems a bit off, is this just a feeling?

**Comment by mintbomb27** [comment]
I've added a white bg one next to the dark one. Also, I've tried to create the logo again centering the F. If you think it looks better, I can replace with that.

**Comment by pBouillon** [comment]
That's awesome, thanks a lot!

Could we reduce the gradient width a bit? Also, without the dark background, the gradient on the title might not be necessary.

After that I think this will be perfect, we will just need to replace the logo for the readme/docs and the social card in the docs :smile:

**Comment by mintbomb27** [comment]
I've added two iterations. Let me know which one looks better.

**Comment by pBouillon** [comment]
I prefer the second one, with a smaller shade on the corner
