### ISSUE TITLE
Add this to Awesome Angular List

### ISSUE THREAD

**Issue by jdegand** [pBouillon/ngx-flagr#46]
What category would you put this in?  I have been thinking about adding a `debugging` section or maybe a `prototyping` section.  Interested in your thoughts.

**Comment by pBouillon** [comment]
Hey, glad you like the project 🎉 

Not sure where similar tools would fit, maybe it's missing a dedicated subcategory?
Something like `libraries` or `third-parties`?

**Comment by jdegand** [comment]
I am going to add to `misc` for right now.  It may move to another category later on.
